#!/bin/sh
#SBATCH --job-name=diag-deep-dimacs10
#SBATCH --partition=hfacnormal01
#SBATCH --time=0-00:20:00
#SBATCH --output=/public/home/acs4vb4pqv/ylzl/MWDS-Ant/exp-8/diagnostics/timeout_capture/jobs/slurm-%j-diag-deep-dimacs10.out
#SBATCH --mem=64G
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
set -e
cd "/public/home/acs4vb4pqv/ylzl/MWDS-Ant/exp-8/deep-v6/jobs"
python3 ./goSolver.py 1 900 \
  "/public/home/acs4vb4pqv/ylzl/MWDS-Ant/exp-8/deep-v6/codes/Dual-Deep-v6/dual-deep-v6" "/public/home/acs4vb4pqv/benchmarks/MWDS2026/DIMACS10" "/public/home/acs4vb4pqv/ylzl/MWDS-Ant/exp-8/diagnostics/timeout_capture/result/deep-v6" \
  --cutoff_mem 16 \
  --name_list "/public/home/acs4vb4pqv/ylzl/MWDS-Ant/exp-8/diagnostics/timeout_capture/namelists/deep-dimacs10.txt" \
  --suffix "diag-deep-dimacs10-s2" \
  780 2 90
